# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/babel-types-7.0.4" = {
      name = "_at_types_slash_babel-types";
      packageName = "@types/babel-types";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/babel-types/-/babel-types-7.0.4.tgz";
        sha512 = "WiZhq3SVJHFRgRYLXvpf65XnV6ipVHhnNaNvE8yCimejrGglkg38kEj0JcizqwSHxmPSjcTlig/6JouxLGEhGw==";
      };
    };
    "@types/babylon-6.16.3" = {
      name = "_at_types_slash_babylon";
      packageName = "@types/babylon";
      version = "6.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/babylon/-/babylon-6.16.3.tgz";
        sha512 = "lyJ8sW1PbY3uwuvpOBZ9zMYKshMnQpXmeDHh8dj9j2nJm/xrW0FgB5gLSYOArj5X0IfaXnmhFoJnhS4KbqIMug==";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "acorn-4.0.13" = {
      name = "acorn";
      packageName = "acorn";
      version = "4.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-4.0.13.tgz";
        sha1 = "105495ae5361d697bd195c825192e1ad7f253787";
      };
    };
    "acorn-globals-3.1.0" = {
      name = "acorn-globals";
      packageName = "acorn-globals";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-globals/-/acorn-globals-3.1.0.tgz";
        sha1 = "fd8270f71fbb4996b004fa880ee5d46573a731bf";
      };
    };
    "align-text-0.1.4" = {
      name = "align-text";
      packageName = "align-text";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz";
        sha1 = "0cd90a561093f35d0a99256c22b7069433fad117";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "babel-types-6.26.0" = {
      name = "babel-types";
      packageName = "babel-types";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-types/-/babel-types-6.26.0.tgz";
        sha1 = "a3b073f94ab49eb6fa55cd65227a334380632497";
      };
    };
    "babylon-6.18.0" = {
      name = "babylon";
      packageName = "babylon";
      version = "6.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babylon/-/babylon-6.18.0.tgz";
        sha512 = "q/UEjfGJ2Cm3oKV71DJz9d25TPnq5rhBVL2Q4fA5wcC3jcrdn7+SssEybFIxwAvvP+YCsCYNKughoF33GxgycQ==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "camelcase-1.2.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz";
        sha1 = "9bb5304d2e0b56698b2c758b08a3eaa9daa58a39";
      };
    };
    "center-align-0.1.3" = {
      name = "center-align";
      packageName = "center-align";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/center-align/-/center-align-0.1.3.tgz";
        sha1 = "aa0d32629b6ee972200411cbd4461c907bc2b7ad";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "http://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha1 = "c7ce28f36d4bcd9744e5ffc2c5fcde1c73261fc0";
      };
    };
    "clean-css-4.2.1" = {
      name = "clean-css";
      packageName = "clean-css";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-css/-/clean-css-4.2.1.tgz";
        sha512 = "4ZxI6dy4lrY6FHzfiy1aEOXgu4LIsW2MhwG0VBKdcoGoH/XLFgaHSdLTGr4O8Be6A8r3MOphEiI8Gc1n0ecf3g==";
      };
    };
    "cliui-2.1.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-2.1.0.tgz";
        sha1 = "4b475760ff80264c762c3a1719032e91c7fea0d1";
      };
    };
    "coffee-script-1.12.7" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.12.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.12.7.tgz";
        sha512 = "fLeEhqwymYat/MpTPUjSKHVYYl0ec2mOyALEMLmzr5i1isuG+6jfI2j2d5oBO3VIzgUXgBVIcOT9uH1TFxBckw==";
      };
    };
    "commander-2.18.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.18.0.tgz";
        sha512 = "6CYPa+JP2ftfRU2qkDK+UTVeQYosOg/2GbcjIcKPHfinyOLPVGXu/ovN86RP49Re5ndJK1N0kuiidFFuepc4ZQ==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "constantinople-3.1.2" = {
      name = "constantinople";
      packageName = "constantinople";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/constantinople/-/constantinople-3.1.2.tgz";
        sha512 = "yePcBqEFhLOqSBtwYOGGS1exHo/s1xjekXiinh4itpNQGCu4KA1euPh1fg07N2wMITZXQkBz75Ntdt1ctGZouw==";
      };
    };
    "core-js-2.5.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.7.tgz";
        sha512 = "RszJCAxg/PP6uzXVXL6BsxSXx/B05oJAQ2vkJRjyjrEcNVycaqOmNb5OTxZPE3xa5gwZduqza6L9JOCenh/Ecw==";
      };
    };
    "css-parse-1.7.0" = {
      name = "css-parse";
      packageName = "css-parse";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-parse/-/css-parse-1.7.0.tgz";
        sha1 = "321f6cf73782a6ff751111390fc05e2c657d8c9b";
      };
    };
    "debug-4.0.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.0.1.tgz";
        sha512 = "K23FHJ/Mt404FSlp6gSZCevIbTMLX0j3fmHhUEhQ3Wq0FMODW3+cUSoLdy1Gx4polAf4t/lphhmHH35BB8cLYw==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "doctypes-1.1.0" = {
      name = "doctypes";
      packageName = "doctypes";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctypes/-/doctypes-1.1.0.tgz";
        sha1 = "ea80b106a87538774e8a3a4a5afe293de489e0a9";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "glob-7.0.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.0.6.tgz";
        sha1 = "211bafaf49e525b8cd93260d14ab136152b3f57a";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-expression-3.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-3.0.0.tgz";
        sha1 = "39acaa6be7fd1f3471dc42c7416e61c24317ac9f";
      };
    };
    "is-promise-2.1.0" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz";
        sha1 = "79a2a9ece7f096e80f36d2b2f3bc16c1ff4bf3fa";
      };
    };
    "is-regex-1.0.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.4.tgz";
        sha1 = "5517489b547091b0930e095654ced25ee97e9491";
      };
    };
    "js-stringify-1.0.2" = {
      name = "js-stringify";
      packageName = "js-stringify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-stringify/-/js-stringify-1.0.2.tgz";
        sha1 = "1736fddfd9724f28a3682adc6230ae7e4e9679db";
      };
    };
    "jstransformer-1.0.0" = {
      name = "jstransformer";
      packageName = "jstransformer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransformer/-/jstransformer-1.0.0.tgz";
        sha1 = "ed8bf0921e2f3f1ed4d5c1a44f68709ed24722c3";
      };
    };
    "jstransformer-coffee-script-1.1.1" = {
      name = "jstransformer-coffee-script";
      packageName = "jstransformer-coffee-script";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransformer-coffee-script/-/jstransformer-coffee-script-1.1.1.tgz";
        sha1 = "6455eb2f8b26fdff2abeb1b3c9875e6b1f4f8fa6";
      };
    };
    "jstransformer-markdown-it-2.1.0" = {
      name = "jstransformer-markdown-it";
      packageName = "jstransformer-markdown-it";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransformer-markdown-it/-/jstransformer-markdown-it-2.1.0.tgz";
        sha1 = "69ec30ce4518bed5997b38f027648e8c285e92f7";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "lazy-cache-1.0.4" = {
      name = "lazy-cache";
      packageName = "lazy-cache";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy-cache/-/lazy-cache-1.0.4.tgz";
        sha1 = "a1d78fc3a50474cb80845d3b3b6e1da49a446e8e";
      };
    };
    "linkify-it-2.0.3" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-2.0.3.tgz";
        sha1 = "d94a4648f9b1c179d64fa97291268bdb6ce9434f";
      };
    };
    "lodash-4.17.11" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz";
        sha512 = "cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==";
      };
    };
    "longest-1.0.1" = {
      name = "longest";
      packageName = "longest";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest/-/longest-1.0.1.tgz";
        sha1 = "30a0b2da38f73770e8294a0d22e6625ed77d0097";
      };
    };
    "markdown-it-8.4.2" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "8.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-8.4.2.tgz";
        sha512 = "GcRz3AWTqSUphY3vsUqQSFMbgR38a4Lh3GWlHRh/7MRwz8mcu9n2IO7HOh+bXHrR9kOPDl5RNCaEsrneb+xhHQ==";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "merge-1.2.0" = {
      name = "merge";
      packageName = "merge";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge/-/merge-1.2.0.tgz";
        sha1 = "7531e39d4949c281a66b8c5a6e0265e8b05894da";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "http://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "nolQXZ/4L+bP/UGlkfaIujX9BKxGwmQ9OT4mOt5yvy8iK1h3wqTEJCijzGANTCCl9nWjY41juyAn2K3Q1hLLTg==";
      };
    };
    "pug-2.0.3" = {
      name = "pug";
      packageName = "pug";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug/-/pug-2.0.3.tgz";
        sha1 = "71cba82537c95a5eab7ed04696e4221f53aa878e";
      };
    };
    "pug-attrs-2.0.3" = {
      name = "pug-attrs";
      packageName = "pug-attrs";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-attrs/-/pug-attrs-2.0.3.tgz";
        sha1 = "a3095f970e64151f7bdad957eef55fb5d7905d15";
      };
    };
    "pug-cli-1.0.0-alpha6" = {
      name = "pug-cli";
      packageName = "pug-cli";
      version = "1.0.0-alpha6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-cli/-/pug-cli-1.0.0-alpha6.tgz";
        sha1 = "1ca539ea4ac0ebb69ce4aae84aeed5d64ffe6501";
      };
    };
    "pug-code-gen-2.0.1" = {
      name = "pug-code-gen";
      packageName = "pug-code-gen";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-code-gen/-/pug-code-gen-2.0.1.tgz";
        sha1 = "0951ec83225d74d8cfc476a7f99a259b5f7d050c";
      };
    };
    "pug-error-1.3.2" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-1.3.2.tgz";
        sha1 = "53ae7d9d29bb03cf564493a026109f54c47f5f26";
      };
    };
    "pug-filters-3.1.0" = {
      name = "pug-filters";
      packageName = "pug-filters";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-filters/-/pug-filters-3.1.0.tgz";
        sha1 = "27165555bc04c236e4aa2b0366246dfa021b626e";
      };
    };
    "pug-lexer-4.0.0" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-4.0.0.tgz";
        sha1 = "210c18457ef2e1760242740c5e647bd794cec278";
      };
    };
    "pug-linker-3.0.5" = {
      name = "pug-linker";
      packageName = "pug-linker";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-linker/-/pug-linker-3.0.5.tgz";
        sha1 = "9e9a7ae4005682d027deeb96b000f88eeb83a02f";
      };
    };
    "pug-load-2.0.11" = {
      name = "pug-load";
      packageName = "pug-load";
      version = "2.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-load/-/pug-load-2.0.11.tgz";
        sha1 = "e648e57ed113fe2c1f45d57858ea2bad6bc01527";
      };
    };
    "pug-parser-5.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-5.0.0.tgz";
        sha1 = "e394ad9b3fca93123940aff885c06e44ab7e68e4";
      };
    };
    "pug-runtime-2.0.4" = {
      name = "pug-runtime";
      packageName = "pug-runtime";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-runtime/-/pug-runtime-2.0.4.tgz";
        sha1 = "e178e1bda68ab2e8c0acfc9bced2c54fd88ceb58";
      };
    };
    "pug-strip-comments-1.0.3" = {
      name = "pug-strip-comments";
      packageName = "pug-strip-comments";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-strip-comments/-/pug-strip-comments-1.0.3.tgz";
        sha1 = "f1559592206edc6f85310dacf4afb48a025af59f";
      };
    };
    "pug-walk-1.1.7" = {
      name = "pug-walk";
      packageName = "pug-walk";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-walk/-/pug-walk-1.1.7.tgz";
        sha1 = "c00d5c5128bac5806bec15d2b7e7cdabe42531f3";
      };
    };
    "regenerator-runtime-0.11.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz";
        sha512 = "MguG95oij0fC3QV3URf4V2SDYGJhJnJGqvIIgdECeODCT98wSWDAJ94SSuVpYQUoTcGUIL6L4yNB7j1DFFHSBg==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "resolve-1.8.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.8.1.tgz";
        sha512 = "AicPrAC7Qu1JxPCZ9ZgCZlY35QgFnNqc+0LtbRNxnVw4TXvjQ72wnuL9JQcEBgXkI9JM8MsT9kaQoHcpCRJOYA==";
      };
    };
    "right-align-0.1.3" = {
      name = "right-align";
      packageName = "right-align";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/right-align/-/right-align-0.1.3.tgz";
        sha1 = "61339b722fe6a3515689210d24e14c96148613ef";
      };
    };
    "sax-0.5.8" = {
      name = "sax";
      packageName = "sax";
      version = "0.5.8";
      src = fetchurl {
        url = "http://registry.npmjs.org/sax/-/sax-0.5.8.tgz";
        sha1 = "d472db228eb331c2506b0e8c15524adb939d12c1";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha1 = "c24bc146ca517c1471f5dacbe2571b2b7f9e3346";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "stylus-0.54.5" = {
      name = "stylus";
      packageName = "stylus";
      version = "0.54.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylus/-/stylus-0.54.5.tgz";
        sha1 = "42b9560931ca7090ce8515a798ba9e6aa3d6dc79";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "to-fast-properties-1.0.3" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-1.0.3.tgz";
        sha1 = "b83571fa4d8c25b82e231b06e3a3055de4ca1a47";
      };
    };
    "token-stream-0.0.1" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-0.0.1.tgz";
        sha1 = "ceeefc717a76c4316f126d0b9dbaa55d7e7df01a";
      };
    };
    "uc.micro-1.0.5" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.5.tgz";
        sha512 = "JoLI4g5zv5qNyT09f4YAvEZIIV1oOjqnewYg5D38dkQljIzpPT296dbIGvKro3digYI1bkb7W6EP1y4uDlmzLg==";
      };
    };
    "uglify-js-2.8.29" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "2.8.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-2.8.29.tgz";
        sha1 = "29c5733148057bb4e1f75df35b7a9cb72e6a59dd";
      };
    };
    "uglify-to-browserify-1.0.2" = {
      name = "uglify-to-browserify";
      packageName = "uglify-to-browserify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz";
        sha1 = "6e0924d6bda6b5afe349e39a6d632850a0f882b7";
      };
    };
    "void-elements-2.0.1" = {
      name = "void-elements";
      packageName = "void-elements";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/void-elements/-/void-elements-2.0.1.tgz";
        sha1 = "c066afb582bb1cb4128d60ea92392e94d5e9dbec";
      };
    };
    "window-size-0.1.0" = {
      name = "window-size";
      packageName = "window-size";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz";
        sha1 = "5438cd2ea93b202efa3a19fe8887aee7c94f9c9d";
      };
    };
    "with-5.1.1" = {
      name = "with";
      packageName = "with";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/with/-/with-5.1.1.tgz";
        sha1 = "fa4daa92daf32c4ea94ed453c81f04686b575dfe";
      };
    };
    "wordwrap-0.0.2" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz";
        sha1 = "b79669bb42ecb409f83d583cad52ca17eaa1643f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "yargs-3.10.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "3.10.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/yargs/-/yargs-3.10.0.tgz";
        sha1 = "f7ee7bd857dd7c1d2d38c0e74efbd681d1431fd1";
      };
    };
  };
  args = {
    name = "hxrts";
    packageName = "hxrts";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."@types/babel-types-7.0.4"
      sources."@types/babylon-6.16.3"
      sources."acorn-3.3.0"
      (sources."acorn-globals-3.1.0" // {
        dependencies = [
          sources."acorn-4.0.13"
        ];
      })
      sources."align-text-0.1.4"
      sources."amdefine-1.0.1"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."argparse-1.0.10"
      sources."asap-2.0.6"
      sources."babel-runtime-6.26.0"
      sources."babel-types-6.26.0"
      sources."babylon-6.18.0"
      sources."balanced-match-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."camelcase-1.2.1"
      sources."center-align-0.1.3"
      sources."chalk-1.1.3"
      sources."character-parser-2.2.0"
      sources."clean-css-4.2.1"
      sources."cliui-2.1.0"
      sources."coffee-script-1.12.7"
      sources."commander-2.18.0"
      sources."concat-map-0.0.1"
      sources."constantinople-3.1.2"
      sources."core-js-2.5.7"
      sources."css-parse-1.7.0"
      sources."debug-4.0.1"
      sources."decamelize-1.2.0"
      sources."doctypes-1.1.0"
      sources."entities-1.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."esutils-2.0.2"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."glob-7.0.6"
      sources."has-1.0.3"
      sources."has-ansi-2.0.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."is-buffer-1.1.6"
      (sources."is-expression-3.0.0" // {
        dependencies = [
          sources."acorn-4.0.13"
        ];
      })
      sources."is-promise-2.1.0"
      sources."is-regex-1.0.4"
      sources."js-stringify-1.0.2"
      sources."jstransformer-1.0.0"
      sources."jstransformer-coffee-script-1.1.1"
      sources."jstransformer-markdown-it-2.1.0"
      sources."kind-of-3.2.2"
      sources."lazy-cache-1.0.4"
      sources."linkify-it-2.0.3"
      sources."lodash-4.17.11"
      sources."longest-1.0.1"
      sources."markdown-it-8.4.2"
      sources."mdurl-1.0.1"
      sources."merge-1.2.0"
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."ms-2.1.1"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."promise-7.3.1"
      sources."pug-2.0.3"
      sources."pug-attrs-2.0.3"
      sources."pug-cli-1.0.0-alpha6"
      sources."pug-code-gen-2.0.1"
      sources."pug-error-1.3.2"
      sources."pug-filters-3.1.0"
      sources."pug-lexer-4.0.0"
      sources."pug-linker-3.0.5"
      sources."pug-load-2.0.11"
      sources."pug-parser-5.0.0"
      sources."pug-runtime-2.0.4"
      sources."pug-strip-comments-1.0.3"
      sources."pug-walk-1.1.7"
      sources."regenerator-runtime-0.11.1"
      sources."repeat-string-1.6.1"
      sources."resolve-1.8.1"
      sources."right-align-0.1.3"
      sources."sax-0.5.8"
      sources."source-map-0.6.1"
      sources."sprintf-js-1.0.3"
      sources."strip-ansi-3.0.1"
      (sources."stylus-0.54.5" // {
        dependencies = [
          sources."source-map-0.1.43"
        ];
      })
      sources."supports-color-2.0.0"
      sources."to-fast-properties-1.0.3"
      sources."token-stream-0.0.1"
      sources."uc.micro-1.0.5"
      (sources."uglify-js-2.8.29" // {
        dependencies = [
          sources."source-map-0.5.7"
        ];
      })
      sources."uglify-to-browserify-1.0.2"
      sources."void-elements-2.0.1"
      sources."window-size-0.1.0"
      sources."with-5.1.1"
      sources."wordwrap-0.0.2"
      sources."wrappy-1.0.2"
      sources."yargs-3.10.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "hxrts.com";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}